### PR TITLE
Add clippy checks on push

### PR DESCRIPTION
**Pull request by aidenfoxivey**

### CODE REVIEW

**Comment by OliverFM** [comment]
Thanks for adding this!

**Comment by aidenfoxivey** [comment]
I think it's probably advantageous to separate this to a different job?

**Comment by OliverFM** [comment]
> I think it's probably advantageous to separate this to a different job?

yeah maybe the best way to do this is to disable all the warnings that the code currently produces, then fix them as we go along.
Otherwise this will probably never be merged

**Comment by aidenfoxivey** [comment]
Fair enough, that's a good perspective. I'll modify and submit by EOD.

**Comment by aidenfoxivey** [comment]
This should probably work? I hope at least. Let me know if there are any issues here.

**Comment by OliverFM** [comment]
@aidenfoxivey this looks great! I will merge this now, and we can make it a required check once I have fixed the remaining lint issues!

**Pull request merged**
